### ISSUE TITLE
Can't see unworn 1000 Gear

### ISSUE THREAD

**Issue by timberwolf146** [SimCMinMax/SimPermut#10]
When attempting to select legendary items at 1000 ilvl, they do not appear unless the character is currently wearing them.  Images attached show the item being worn via simpermut (with 1000 legendary in bags).
![wowscrnshot_112917_020041](https://user-images.githubusercontent.com/34087393/33362261-96ecc1ee-d4a9-11e7-915c-41336ac78121.jpg)
![wowscrnshot_112917_020028](https://user-images.githubusercontent.com/34087393/33362262-96f46ee4-d4a9-11e7-9f2e-b16eca3eb5ac.jpg)

**Comment by Kutikuti** [comment]
yeah, i forgot to bump the ilvl threshold to 1k. It will be corrected today

**Comment by Kutikuti** [comment]
Fixed in https://github.com/SimCMinMax/SimPermut/commit/288f302de4e50a6c672c52053d45ddb2c1b13883
