### ISSUE TITLE
LUA error after patch

### ISSUE THREAD

**Issue by rixanne** [SimCMinMax/SimPermut#12]
tried to invoke simpermut by /simpermut and got the following along with a blank simpermut screen with no options.

Date: 2018-01-16 18:25:56
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SimPermut\core.lua line 3243:
   attempt to concatenate local 'playerArtifact' (a nil value)
Debug:
   SimPermut\core.lua:3243: GetBaseString()
   SimPermut\core.lua:1936: InitGearFrame()
   SimPermut\core.lua:267: BuildFrame()
   SimPermut\core.lua:190: ?()
   ..\FrameXML\ChatFrame.lua:4547:
      ..\FrameXML\ChatFrame.lua:4494
   [C]: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4215:
      ..\FrameXML\ChatFrame.lua:4214
   [C]: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4251: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
self = <table> {
 GetTableLink = <function> defined @Interface\AddOns\SimPermut\core.lua:2615
 BuildGearFrame = <function> defined @Interface\AddOns\SimPermut\core.lua:284
 EnableModule = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 CheckItemCount = <function> defined @Interface\AddOns\SimPermut\core.lua:2197
 baseName = "SimPermut"
 BuildItemFrame = <function> defined @Interface\AddOns\SimPermut\core.lua:1950
 ExtraData = <table> {
 }
 BuildResultFrame = <function> defined @Interface\AddOns\SimPermut\core.lua:1882
 Printf = <function> defined @Interface\AddOns\AutoLog\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 GetAllPermutations = <function> defined @Interface\AddOns\SimPermut\core.lua:2761
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 DisableModule = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 GenerateCrucibleData = <function> defined @Interface\AddOns\SimPermut\core.lua:3087
 RegisterMessage = <function> defined @Interface\AddOns\AutoLog\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\AutoLog\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 BuildDungeonJournalFrame = <function> defined @Interface\AddOns\SimPermut\core.lua:1382
 GenerateRelic = <function> defined @Interface\AddOns\SimPermut\core.lua:2088
 BuildNetherlightFrame = <function> defined @Interface\AddOns\SimPermut\core.lua:907
 GetListItem = <function> defined @Interface\AddOns\SimPermut\core.lua:2523
 CheckUsability = <function> defined @Interface\AddOns\SimPermut\core.lua:3293
 SetEnabledState = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 GenerateTalents = <function> defined @Interface\AddOns\SimPermut\core.lua:2070
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\AutoLog\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 Generate = <function> defined @Interface\AddOns\SimPermut\core.lua:2024
 GetItemString = <function> defined @Interface\AddOns\SimPermut\core.lua:2234
 IterateModules = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 ReorganizeEquip = <function> defined @Interface\AddOns\SimPermut\core.lua:2773
 GetPowerData = <function> defined @Interface\AddOns\SimPermut\core.lua:3468
 PreparePermutations = <function> defined @Interface\AddOns\SimPermut\core.lua:2803
 OnInitialize = <function> defined @Interface\AddOns\SimPermut\core.lua:205
 NewModule = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 AddSpacer = <function> defined @Interface\AddOns\SimPermut\core.lua:2213
 GetModule = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 GenerateRelicString = <function> defined @Interface\AddOns\SimPermut\core.lua:2995
 defaultModuleLibraries = <table> {
 }
 BuildRelicFrame = <function> defined @Interface\AddOns\SimPermut\core.lua:580
 UnregisterChatCommand = <function> defined @Interface\AddOns\AutoLog\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 GetCopyName = <function> defined @Interface\AddOns\SimPermut\core.lua:3175
 GenerateCruciblePermutation = <function> defined @Interface\AddOns\SimPermut\core.lua:2122
 BuildFrame = <function> defined @Interface\AddOns\SimPermut\core.lua:218
 GetName = <function> defined @Interface\AddOns\Dominos\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 GenerateCrucible = <function> defined @Interface\AddOns\SimPermut\core.lua:2105
 GetItemStrings = <function> defined @Interface\AddOns\SimPermut\core.lua:2493
 name = "SimPermut"
 GenerateCruciblePermutationStrings = <function> defined @Interface\AddOns\SimPermut\core.lua:3546
 isEquiped = <function> defined @Interface\AddOns\SimPermut\core.lua:3527
 orderedModules = <table> {
 }
 AddItemLink = <function> defined @Interface\AddOns\SimPermut\core.lua:3434
 Disable = <functio
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  ACP, vr250 
  AutoLog, vv7.3.1.0
  Coordinates, v1.23
  CrucibleWeight, v18
  DBMCore, v7.3.17
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dominos, v7.3.2
  DominosCast, v
  DominosRoll, v
  ExRT, v3900
  FocusInterruptSounds, v4.0
  GTFO, v4.44.2
  HideTalkingHead, vv1.0.5
  Inventorian, v7.3.0.0
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  MizusRaidTracker, vv0.73.3
  MoveAnything, v16.3.1
  NiceDamage, v20400
  OmniCC, v7.3.1
  Outfitter, v5.19.1
  Overachiever, v0.99.10
  Pawn, v2.2.17a
  PhoenixStyle, v
  Postal, vv3.5.8
  Prat30, vr1082      
  Prat30Libraries, v
  Scrap, v13.6
  SexyMap, vv7.3.0
  SimPermut, v1.14.13
  Simulationcraft, v1.8.4
  Skada, v1.7.2
  SlideBar, v7.3.1 (<%codename%>)
  SpellFlashCore, v2.1.6
  TalentSetManager, v
  TomTom, vv70300-1.0.0
  WeakAuras, v2.5.3
  WhoPulled, v1.0.14
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=390)

**Comment by thunderchylde** [comment]
Tracing the code back it looks like the assignment is:

	local playerArtifact = PersoLib:GetArtifactString()

core.lua -- line 3215

Looking at that function the only nil response is:

	if not itemId then
		self:CloseArtifactFrame(artifactFrameOpen, correctArtifactOpen)
		return nil
	end

	local artifactId = ExtraData.ArtifactTable[itemId]
	if artifactId == nil then
		self:CloseArtifactFrame(artifactFrameOpen, correctArtifactOpen)
		return nil
	end

**Comment by Kutikuti** [comment]
yeah they changed something with the artifact, i'll make an update soon

**Comment by Kutikuti** [comment]
Fixed with https://github.com/SimCMinMax/SimPermut/commit/f0662d2f8c9ada92c680640525320989e2daae35
