### ISSUE TITLE
Suggestion: Add support for Warlords of Draenor cloak enchants

### ISSUE THREAD

**Issue by eyriewow** [SimCMinMax/SimPermut#13]
The cloak enchants from Warlords of Draenor provide 100 of any secondary stat and 2% movement speed (for example [Gift of Critical Strike](http://www.wowhead.com/spell=158884/gift-of-critical-strike)).

Considering many specs heavily benefit from secondary stats these cloak enchants have a chance to outperform the current 200 main stat Legion enchants. I think it would make sense to add the WoD enchants   to the dropdown list of available enchants for cloaks.

**Comment by Kutikuti** [comment]
Added in https://github.com/SimCMinMax/SimPermut/commit/fb5deb3aab1eaaa252bd57695b2e7f9a970dc265
