### ISSUE TITLE
Suggestion: Manually add items to list

### ISSUE THREAD

**Issue by Speaker1264** [SimCMinMax/SimPermut#14]
It would be nice if we could manually add items to our list of current items using the item ID.  I know it's possible to just edit the simc import string, but that can be extremely time consuming depending on how many different items we are simulating.  It would be nice if the addon could just do it for us.

Example: I want to compare an ilvl 1000 Golganneth's Vitality to my own trinkets.  I could just hit a button to manually add the item.  Type in the ID like so, 154174 and optionally the bonus 1532/3983, then click add and the item will be added to my current trinkets.  The item would be saved and I could use it to generate as many SimC import strings as I want.  Maybe a few weeks go by and I no longer need the item for comparison sake I can then delete it from my saved items.

**Comment by Kutikuti** [comment]
That's already possible, you can do that in the add item menu.
You have to link the item from dungeon journal for example. You can then set the item level and if it has a gem or not.
Then the item will be available in the main page

**Comment by Speaker1264** [comment]
Oh, derp... I guess I totally missed it.  Thanks Kutikuti.
