### ISSUE TITLE
LUA Error when trying to generate a string with more than just equipped items.

### ISSUE THREAD

**Issue by mikeno1** [SimCMinMax/SimPermut#2]
So essentially I get the following LUA error occasionally when trying to generate a string, I've only noticed it happening when I select additional items to the ones currently equipped.

Even when the LUA error doesn't appear the generate will only provide a string for my equipped items no matter what I have selected.

The LUA error that I do get is as follows:

Date: 2017-05-13 20:57:59
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SimPermut\core.lua line 1110:
   attempt to concatenate local 'enchantID' (a nil value)
Debug:
   SimPermut\core.lua:1110: GetItemString()
   SimPermut\core.lua:1594: GetPermutationString()
   SimPermut\core.lua:899: Generate()
   SimPermut\core.lua:389:
      SimPermut\core.lua:388
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[4]"]:9:
      [string "safecall Dispatcher[4]"]:5
   (tail call): ?
   ...ce\AddOns\GottaGoFast\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: Fire()
   ...Fast\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:28:
      ...Fast\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:25
Locals:
None
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  NPCScanOverlay, v7.1.0.1
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucScanData, v7.4.5714 (TasmanianThylacine)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BigBrother, v4.2.1
  Configator, v5.1.DEV.406(/embedded)
  ConsLegion, v1.28
  CoShelper, v1.3
  DBMCore, v7.2.6
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.47
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  ExRT, v3855
  GarrisonMissionManager, vv55
  GottaGoFast, v26500
  GottaGoFastHistory, v26500
  GTFO, v4.42.13
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  MikScrollingBattleText, v5.7.147
  NPCScan, v7.2.0.2
  Oilvl, v6.5.4
  Omen, v3.1.12
  Overachiever, v0.99.7
  OverachieverTabs, v0.99.7
  Pawn, v2.2.4
  PersonalLootHelper, v1.29
  Postal, vv3.5.8
  RaidAchievement, v
  RaidAchievementOldModules, v
  RCLootCouncil, v2.3.2
  RSA, v3.2752
  RSAPaladin, v
  ServerHop, v7.2.4.1
  SimPermut, v1.11
  Simulationcraft, v1.7.1
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70200-1.0.0
  WeakAuras, v2.4.1
  WorldQuestGroupFinder, v0.24.3
  WorldQuestsList, v34
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=bb9)

Thanks,
Michael

**Comment by mikeno1** [comment]
Quick note, I've tried uninstalling and reinstalling the addon, this didn't help. I've also tried doing it with only SimPermut enabled and all other addons disabled, this also did not help.

**Comment by Kutikuti** [comment]
thanks for the report, already fixed it, just have to make a release, this will be coming tonight

**Comment by mikeno1** [comment]
Ohh awesome! Looking forward to it!
