### ISSUE TITLE
Report type -> Item Names doesn't work with russian item names

### ISSUE THREAD

**Issue by Elfrey** [SimCMinMax/SimPermut#4]
When I pick "Report type -> Item Names", I get unreadable string
```
copy=-___,Base
shoulder=,id=144326,enchant_id=5441,bonus_id=3529/3530/1811
waist=,id=142420,bonus_id=3508/1808/1522/3336,gem_id=130220

copy=-___-__,Base
shoulder=,id=144326,enchant_id=5441,bonus_id=3529/3530/1811
waist=,id=142420,bonus_id=3508/1808/1522/3336,gem_id=130220
feet=,id=134464,bonus_id=3536/1562/3337
```

It's not a big deal, but after siming it's kinda hard to track in results like that 
![84b03c5c6f 1](https://user-images.githubusercontent.com/519766/27820273-5385d1fe-60b7-11e7-93ce-56193ed19159.png)

**Comment by Kutikuti** [comment]
Fixed in the next update. I have a couple more thing to fix, I will probably make a release tonight or tomorrow
