### ISSUE TITLE
Enchants / Gems

### ISSUE THREAD

**Issue by homezonebenny** [SimCMinMax/SimPermut#5]
I have a short question.
I wanted to compare my "base gear" (current gear I wear right now) with "Base Gear + Enchants / Gems".
Therefore I made a sim just with my current equiped gear to see the DPS.
After that I select all the enchants below in the /simpermut and check "Replace current enchants/gems".
But when I press generate, I do not get a different code than normal (no enchants in it).

Any ideas how to do that?
I know this is pretty uncommon. But I just want a quick test to see how much enchants / gems would change.
I do not plan to enchant my low ilvl char. But I would really want to know how much it could bring.

Maybe you could implement this into Simpermut.
So that selected enchants (who are not on the current gear) will set into the code for a sim.﻿

**Comment by Kutikuti** [comment]
To replace current enchants, just go in the option panel and tick the "replace current enchant/gems for base profile".
You next generation should replace enchant for the gear you have equiped

**Comment by homezonebenny** [comment]
I made a screenshot to show it seems not working:
http://imgur.com/a/WkhWS

First just base gear.
2nd with gems selected. Replace selected aswell. Generate and no code change.

**Comment by homezonebenny** [comment]
The issue is still there.
When you open:
/simpermut
And then you select all the enchants / gems. And you enable "Replace current enchants/gems" and you press "Generate" button it just generate a "base gear" without ANY enchants  / gems.

IF you set (and that's important) one other item into the list.
Like for example an other chest and you press "Generate" button.
Then it exports the enchants / gems!
Like "Base
neck=,id=147263,enchant_id=5890,"

Please test it like I wrote above.
WITHOUT adding ANY other armor piece.
Just open /simpermut and DO NOT select any armor piece.
Just enable the enchants / gems. And you'll see it exports NO enchants /  gems.

So if you want to compare your current gear vs current gear WITH enchants / gems.
It's not exporting it.

I KNOW it's not common that you want to compare this.
Since in high raid gear, you always have to compare another piece, and you are always enchanted / gemed. So this is not a "big issue". But it is still something which is "not working".
