### ISSUE TITLE
Wrong ilevel

### ISSUE THREAD

**Issue by Llamatron2112** [SimCMinMax/SimPermut#6]
When doing a sim including an ilvl 915 Stormrage Signet Ring (http://www.wowhead.com/item=150524/stormrage-signet-ring) from the Black Temple timewalking event, the detected ilevel is wrong in SimPermut.

For that item, the official simc addon outputs:
finger1=,id=150524,enchant_id=5427,bonus_id=3589/3590,drop_level=110
and the item shows as ilevel 915 as it should in the gear list

and SimPermut:
finger1=,id=150524,enchant_id=5427,bonus_id=3589/3590
resulting in a ilevel 151 item in the gear list

**Comment by Kutikuti** [comment]
Hi, this will be added in the next update. Unfortunatly i'm currently on vacation, so i can't test what i wrote. If you want, you can download the github version of the addon and test it.

**Comment by Llamatron2112** [comment]
This has fixed this issue apparently, thanks for being that fast :)

**Comment by Kutikuti** [comment]
just tracing it : there is an issue if the item ilvl (base, not corrected with drop_level) is not in the ilvl threshold, it will not be listed.

**Comment by Llamatron2112** [comment]
I'm up for testing changes if you need.
