### ISSUE TITLE
Force enchants doesn't appear to be functioning

### ISSUE THREAD

**Issue by JoeMShanahan** [SimCMinMax/SimPermut#7]
See screenie:

![ybzddwz 1](https://user-images.githubusercontent.com/29176664/29003381-db1777fc-7aad-11e7-8ed6-90966e73dd06.png)

As you can see, enchants have not be put on the rings when as far as I can see, they should have? 

I believe the problem is here is the the current loadout doesn't have it's gems/enchants swapped when ticking "Replace current enchant/gems" - feels like it should?

As a feature request also: can the process of simming enchants/gems combinations be streamlined?

**Comment by Kutikuti** [comment]
Hi, for the base profil to be modified by enchants/gems, you have to go to the option pannel an tick "replace enchants/gems for equiped gear"

**Comment by Kutikuti** [comment]
For your request, i'll be doing a UI rework thes coming weeks so it will be part of it.
